// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    // This tells Prisma to use ts-node to run your seed file
    seed: 'ts-node --compiler-options {"module":"CommonJS"} ./prisma/seed.ts',
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
